### ISSUE TITLE
SFP detection broken (?) on Quanta LB9

### ISSUE THREAD

**Issue by capveg** [opennetworklinux/ONL#76] opened 2015-02-20 21:26 UTC
First reported by @nshopik , this is still true with the latest version:

root@onl-powerpc:~# cat /etc/onl_version 
Open Network Linux  23f333b (powerpc.all,2015.02.17.10.42,23f333b539b1b4dfdf3b9600d503f818651a8860)

Symptoms:
sfpdump (lower level) utility correctly shows that the SFP is plugged in:
root@onl-powerpc:~# sfpdump 
SFP port 49:
SFP port 50:
SFP port 51:
SFP port 52:
00000000  03 04 07 00 00 00 08 00  00 00 00 01 0d 00 00 00  |................|
00000010  00 00 64 00 4f 45 4d 20  20 20 20 20 20 20 20 20  |..d.OEM         |
00000020  20 20 20 20 00 20 20 20  53 46 50 2d 54 20 20 20  |    .   SFP-T   |
00000030  20 20 20 20 20 20 20 20  31 31 2e 30 00 00 00 f3  |        11.0....|
00000040  00 00 00 00 45 43 31 34  30 36 30 38 39 36 36 35  |....EC1406089665|
00000050  20 20 20 20 31 34 30 37  31 35 20 20 00 00 00 87  |    140715  ....|
00000060  00 00 11 8a 67 43 ee 71  97 a0 f5 9e 08 57 6f 94  |....gC.q.....Wo.|
00000070  58 38 0f 00 00 00 00 00  00 00 00 00 cc 49 f9 bf  |X8...........I..|
00000080  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00000100

But the higher level utility `onlpdump -r` doesn't show the SFP being plugged in.  Probably an implementation problem in the Quanta LB9 ONLP driver or an ONL packaging/building problem.

**Comment by jnealtowns** [comment] 2015-02-20 21:45
*onlpdump -r *does not include any SFP information in its output.

Run *onlpdump* (no options).

**Comment by capveg** [comment] 2015-02-20 21:53
Still no joy:
root@onl-powerpc:~# onlpdump 
[snip]
SFPs:
  Presence Bitmap: Error: E_UNSUPPORTED
  RX_LOS Bitmap: Error: E_UNSUPPORTED

Port 48: Error: E_MISSING
Port 49: Error: E_MISSING
Port 50: Error: E_MISSING
Port 51: Error: E_MISSING

**Comment by jnealtowns** [comment] 2015-02-20 22:27
Whoops. The root of the problem is that the ONLP implementation for the LB9
does not include the GPIO initializations for the SFP presence bits.

**Comment by nshopik** [comment] 2015-02-21 09:07
Is this only for LB9? T3048-LY2 isn't affected?

**Comment by jnealtowns** [comment] 2015-02-21 19:55
Yes, LY2 will also be affected. The fix for the LY2 is also in progress.

**Comment by jnealtowns** [comment] 2015-02-21 20:11
opennetlinux.org/binaries/latest has the fix for the LB9.

**Comment by capveg** [comment] 2015-02-23 18:19
Thanks Jeff!  Just to clarify, your patch fixes things for LY2 as well,
right?

Thanks,

- Rob
.

On Sat, Feb 21, 2015 at 12:11 PM, Jeffrey Townsend <notifications@github.com

**Comment by jnealtowns** [comment] 2015-02-23 18:21
No. The LY2 still needs to be fixed.

**Comment by nshopik** [comment] 2015-02-24 10:12
@jnealtowns I've tried onl-c0611c8-powerpc-all.2015.02.20.15.09.installer build this is what I get now.

```
SFPs:
  Presence Bitmap: Error: E_UNSUPPORTED
  RX_LOS Bitmap: Error: E_UNSUPPORTED

Port 48: Present, Status Unavailable [ E_UNSUPPORTED ]
eeprom:
  0000: 03 04 21 00 00 00 00 00 04 00 00 00 67 00 00 00 
  0010: 00 00 02 00 4f 45 4d 20 20 20 20 20 20 20 20 20 
  0020: 20 20 20 20 00 00 40 20 44 41 2d 53 46 50 2d 50 
  0030: 6c 75 73 2d 32 6d 20 20 4e 20 20 20 00 00 00 9c 
  0040: 00 00 00 00 53 44 38 44 37 36 30 30 31 34 20 20 
  0050: 20 20 20 20 31 33 30 38 32 31 20 20 00 00 00 74 
  0060: 00 00 08 09 82 c4 7e b6 7d b0 5f e8 5d 53 03 ab 
  0070: e6 eb cd 00 00 00 00 00 00 00 00 00 7b a6 b5 9d 
  0080: 43 4f 50 51 41 41 34 4a 41 41 33 37 2d 30 39 36 
  0090: 30 2d 30 32 56 30 32 20 01 00 46 00 00 00 00 c9 
  00a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00c0: 53 46 50 2d 48 31 30 47 42 2d 43 55 32 4d 20 20 
  00d0: 20 20 20 20 30 38 00 00 00 00 00 00 00 00 00 b4 
  00e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Port 49: Present, Status Unavailable [ E_UNSUPPORTED ]
eeprom:
  0000: 03 04 21 00 00 00 00 00 04 00 00 00 67 00 00 00 
  0010: 00 00 02 00 4f 45 4d 20 20 20 20 20 20 20 20 20 
  0020: 20 20 20 20 00 00 40 20 44 41 2d 53 46 50 2d 50 
  0030: 6c 75 73 2d 32 6d 20 20 4e 20 20 20 00 00 00 9c 
  0040: 00 00 00 00 53 44 38 44 37 36 30 30 31 34 20 20 
  0050: 20 20 20 20 31 33 30 38 32 31 20 20 00 00 00 74 
  0060: 00 00 08 09 82 c4 7e b6 7d b0 5f e8 5d 53 03 ab 
  0070: e6 eb cd 00 00 00 00 00 00 00 00 00 7b a6 b5 9d 
  0080: 43 4f 50 51 41 41 34 4a 41 41 33 37 2d 30 39 36 
  0090: 30 2d 30 32 56 30 32 20 01 00 46 00 00 00 00 c9 
  00a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00c0: 53 46 50 2d 48 31 30 47 42 2d 43 55 32 4d 20 20 
  00d0: 20 20 20 20 30 38 00 00 00 00 00 00 00 00 00 b4 
  00e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

```

**Comment by nshopik** [comment] 2015-02-24 10:16
48 and 49 ports only have SFP inserted, I'm not sure if it should report "present" for empty sfp ports

**Comment by nshopik** [comment] 2015-02-24 13:53
I don't know if this is related but ORC now segfaults for me.
```
root@onl-powerpc:~# gdb orc
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "powerpc-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/orc...Reading symbols from /usr/lib/debug/.build-id/32/60c30fba05d3b9149299f617959c73f4803a55.debug...done.
done.
(gdb) run
Starting program: /usr/sbin/orc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/powerpc-linux-gnu/libthread_db.so.1".
LOG:        load_driver.c:79  :: Found driver at: /usr/share/orc/drivers/orc_brcm.so

Program received signal SIGSEGV, Segmentation fault.
0x100265d4 in aim_pvs_stderr ()
```

**Comment by capveg** [comment] 2015-02-25 18:06
Confirmed that onlpdump has the behavior @nshopik described.

@jnealtowns : I have our lb9-1 box setup with ONL and an SPF inserted into port 51 if you want to dig into this.

Relevant subset of onlpdump from lb9-1:

Port 50: Present, Status Unavailable [ E_UNSUPPORTED ]
06-30 20:34:36.588504 [onlplib] Failed to read EEPROM file '/sys/devices/e0000000.soc8541/e0003000.i2c/i2c-0/i2c-3/3-0050/eeprom'
eeprom:
  0000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Port 51: Present, Status Unavailable [ E_UNSUPPORTED ]
eeprom:
  0000: 03 04 07 00 00 00 08 00 00 00 00 01 0d 00 00 00 
  0010: 00 00 64 00 4f 45 4d 20 20 20 20 20 20 20 20 20 
  0020: 20 20 20 20 00 20 20 20 53 46 50 2d 54 20 20 20 
  0030: 20 20 20 20 20 20 20 20 31 31 2e 30 00 00 00 f3 
  0040: 00 00 00 00 45 43 31 34 30 36 30 38 39 36 36 35 
  0050: 20 20 20 20 31 34 30 37 31 35 20 20 00 00 00 87 
  0060: 00 00 11 8a 67 43 ee 71 97 a0 f5 9e 08 57 6f 94 
  0070: 58 38 0f 00 00 00 00 00 00 00 00 00 cc 49 f9 bf 
  0080: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
  0090: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
  00a0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
  00b0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
  00c0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
  00d0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
  00e0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
  00f0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff

**Comment by jnealtowns** [comment] 2015-03-03 03:13
There was a bug in the (new) gpio initialization code for the LB9. The
issue has been fixed in the latest binaries.

**Comment by nshopik** [comment] 2015-03-04 10:29
Latest build looks better. But I'm not sure correctly understand what this is about `Status Unavailable [ E_UNSUPPORTED ]` If this means some additional data (DOM?) not present then its probably fine and we can close issue.

```
FPs:
  Presence Bitmap: Error: E_UNSUPPORTED
  RX_LOS Bitmap: Error: E_UNSUPPORTED

Port 48: Present, Status Unavailable [ E_UNSUPPORTED ]
eeprom:
  0000: 03 04 21 00 00 00 00 00 04 00 00 00 67 00 00 00 
  0010: 00 00 02 00 4f 45 4d 20 20 20 20 20 20 20 20 20 
  0020: 20 20 20 20 00 00 40 20 44 41 2d 53 46 50 2d 50 
  0030: 6c 75 73 2d 32 6d 20 20 4e 20 20 20 00 00 00 9c 
  0040: 00 00 00 00 53 44 38 44 37 36 30 30 31 34 20 20 
  0050: 20 20 20 20 31 33 30 38 32 31 20 20 00 00 00 74 
  0060: 00 00 08 09 82 c4 7e b6 7d b0 5f e8 5d 53 03 ab 
  0070: e6 eb cd 00 00 00 00 00 00 00 00 00 7b a6 b5 9d 
  0080: 43 4f 50 51 41 41 34 4a 41 41 33 37 2d 30 39 36 
  0090: 30 2d 30 32 56 30 32 20 01 00 46 00 00 00 00 c9 
  00a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00c0: 53 46 50 2d 48 31 30 47 42 2d 43 55 32 4d 20 20 
  00d0: 20 20 20 20 30 38 00 00 00 00 00 00 00 00 00 b4 
  00e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Port 49: Present, Status Unavailable [ E_UNSUPPORTED ]
eeprom:
  0000: 03 04 21 00 00 00 00 00 04 00 00 00 67 00 00 00 
  0010: 00 00 02 00 4f 45 4d 20 20 20 20 20 20 20 20 20 
  0020: 20 20 20 20 00 00 40 20 44 41 2d 53 46 50 2d 50 
  0030: 6c 75 73 2d 32 6d 20 20 4e 20 20 20 00 00 00 9c 
  0040: 00 00 00 00 53 44 38 44 37 36 30 30 31 34 20 20 
  0050: 20 20 20 20 31 33 30 38 32 31 20 20 00 00 00 74 
  0060: 00 00 08 09 82 c4 7e b6 7d b0 5f e8 5d 53 03 ab 
  0070: e6 eb cd 00 00 00 00 00 00 00 00 00 7b a6 b5 9d 
  0080: 43 4f 50 51 41 41 34 4a 41 41 33 37 2d 30 39 36 
  0090: 30 2d 30 32 56 30 32 20 01 00 46 00 00 00 00 c9 
  00a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00c0: 53 46 50 2d 48 31 30 47 42 2d 43 55 32 4d 20 20 
  00d0: 20 20 20 20 30 38 00 00 00 00 00 00 00 00 00 b4 
  00e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Port 50: Missing.
Port 51: Missing.
```

**Comment by jnealtowns** [comment] 2015-03-04 16:11
The ONLP APIs support retrieving SFP signal indicators, such as  TX_FAULT,
TX_DISABLE, and RX_LOS.

The Status Unavailable [ E_UNSUPPORTED ] portion of the dump means the
implementation itself does not support retrieving this data.

I think its important to mention that the onlpdump tool (at least invoked
in this way) is more of a developer and system debug tool, rather than
something you would expect a system user to understand. The "user friendly"
version of the platform information can be displayed as follows:

root@onl-powerpc:~# *onlpdump -r*
Fan 1
Description: Right
State: Present
Status: Running.
RPM: 11713.
Speed: 80%.
Airflow: Front-to-Back.
Fan 2
Description: Center Right
State: Present
Status: Running.
RPM: 12053.
Speed: 83%.
Airflow: Front-to-Back.
Fan 3
Description: Center Left
State: Present
Status: Running.
RPM: 5128.
Speed: 35%.
Airflow: Front-to-Back.
Fan 4
Description: Left
State: Present
Status: Running.
RPM: 5320.
Speed: 36%.
Airflow: Front-to-Back.
Thermal 1
Description: Chassis Thermal 1
Status: Sensor Functional
Temperature: 31.0 C.
Thermal 2
Description: Chassis Thermal 2
Status: Sensor Functional
Temperature: 32.0 C.
Thermal 3
Description: Chassis Thermal 3
Status: Sensor Functional
Temperature: 30.0 C.
Thermal 4
Description: Chassis Thermal 4
Status: Sensor Functional
Temperature: 28.0 C.
Thermal 5
Description: Chassis Thermal 5
Status: Sensor Functional
Temperature: 31.0 C.
PSU 1
Description: PSU-1
State: Missing
PSU 2
Description: PSU-2
State: Present
Status: Running.
Model: PSU-LB9
Type: AC
Vin: 217.5
Vout: 12.4
Iin: 0.3
Iout: 3.2
Pin: 56.0
Pout: 38.0
Fan 6
Description: PSU-2 Fan
State: Present
Status: Running.
RPM: 1824.
Airflow: Front-to-Back.
Thermal 9
Description: PSU-2 Thermal 1
Status: Sensor Functional
Temperature: 31.0 C.
Thermal 10
Description: PSU-2 Thermal 2
Status: Sensor Functional
Temperature: 32.0 C.
Thermal 11
Description: PSU-2 Thermal 3
Status: Sensor Functional
Temperature: 31.0 C.
root@onl-powerpc:~#



I understand that this format does not include the (decoded) SFP
information, but it should. I'll let you know when that modification has
been made.
This modification will display, instead of the raw SFP eeprom data, the
decoded eeprom data suitable for user consumption.
Something similar to this:

Vendor: Amphenol Model: 616740001 SN: CN0V250M48I2WH7 Type: SFP Module:
10GBASE-CR Media: Copper Length: 1



Jeff

**Comment by nshopik** [comment] 2015-03-04 16:21
Thanks Jeff for explanation.

Since parsing eeproom is doesn't tie to LB9, we probably should close this one (issue seems fixed). And create new issue about more user friendly output in `onlpdump -r` which affects all platforms.

Rob? @capveg

**Comment by capveg** [comment] 2015-03-04 21:18
Agreed - closing issue.  I'll open a new issue for the pretty printing the SFP info dump.

**Closed** 2015-03-04 21:18 UTC
