### ISSUE TITLE
Build Issue in make onl-powerpc

### ISSUE THREAD

**Issue by ahmedcs** [opennetworklinux/ONL#121] opened 2015-07-22 13:16 UTC
I am trying to build ONL using the instructions on the webpage

but i get this error after make "onl-powerpc", i am building installer for Edge-Core (Accton) AS4600

export ONL=`pwd` && make -C tools/docker
make[1]: Entering directory `/home/ahmed/ONL/tools/docker'
/usr/bin/docker
docker pull opennetworklinux/onl-build:1.5
Pulling repository opennetworklinux/onl-build
e654655bf44d: Download complete 
21e4345e9035: Download complete 
b3d362b23ec1: Download complete 
f0427e7e4997: Download complete 
d0179fb1f37a: Download complete 
Status: Image is up to date for opennetworklinux/onl-build:1.5
docker run --privileged -t -i \
        -e USER=root \
        -e ONL=/home/ahmed/ONL \
        -v /home/ahmed/ONL:/home/ahmed/ONL \
        -w /home/ahmed/ONL  \
        -h "onl-builder" \
         \
        opennetworklinux/onl-build:1.5 \
        bash -c '/etc/init.d/apt-cacher-ng start && bash'
[ ok ] Starting apt-cacher-ng: apt-cacher-ng.
root@onl-builder:/home/ahmed/ONL# make onl-powerpc
export ONL=`pwd`&& make -C $ONL/builds/components
make[1]: Entering directory`/home/ahmed/ONL/builds/components'
WARNING:onlpkg:no matching packages for initrd-amd64 (amd64)
INFO:onlpkg:found at /home/ahmed/ONL/components/amd64/initrd-amd64/deb/debuild/debian
INFO:onlpkg:can be built locally at /home/ahmed/ONL/components/amd64/initrd-amd64
make[2]: Entering directory `/home/ahmed/ONL/components/amd64/initrd-amd64'
make -C deb
make[6]: warning: -jN forced in submake: disabling jobserver mode.
make -C /home/ahmed/ONL/submodules/loader setup
Building with support for the following platforms: Makefile powerpc-accton-as4600-54t-r0 powerpc-accton-as5610-52x-r0 powerpc-accton-as5700-96x-r0 powerpc-accton-as5710-54x-r0 powerpc-accton-as6700-32x-r0 powerpc-accton-as6700-32x-r1 powerpc-as4600-54t powerpc-as5600-52x powerpc-as5610-52x powerpc-as5710-54x-r0a powerpc-as5710-54x-r0b powerpc-as6700-32x-r0 powerpc-dni-7448-r0 powerpc-quanta-lb9-r0 powerpc-quanta-lb9a-r0 powerpc-quanta-ly2-r0 qemu x86-64-accton-as5712-54x-r0 x86-64-accton-as6712-32x-r0 x86-64-dell-s4000-c2338-r0 x86-64-dell-s6000-s1220-r0
rm -rf rootfiles/lib/platform-config
/home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-Makefile:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-accton-as4600-54t-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-accton-as5610-52x-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-accton-as5700-96x-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-accton-as5710-54x-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-accton-as6700-32x-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-accton-as6700-32x-r1:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-as4600-54t:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-as5600-52x:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-as5610-52x:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-as5710-54x-r0a:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-as5710-54x-r0b:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-as6700-32x-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-dni-7448-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-quanta-lb9-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-quanta-lb9a-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-powerpc-quanta-ly2-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-qemu:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-x86-64-accton-as5712-54x-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-x86-64-accton-as6712-32x-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-x86-64-dell-s4000-c2338-r0:all;   /home/ahmed/ONL/tools/onlpkg.py --build --extract rootfiles platform-config-x86-64-dell-s6000-s1220-r0:all; 
WARNING:onlpkg:no matching packages for platform-config-Makefile (all)
cp patches/busybox-001-init-quiet-restart.patch patches/busybox-002-checkpass-command.patch buildroot/package/busybox/
cp: target`buildroot/package/busybox/' is not a directory
make[7]: **\* [setup] Error 1
make[6]: **\* [/home/ahmed/ONL/submodules/loader/.setup.done] Error 2
make[5]: **\* [component] Error 2
make[4]: **\* [deb] Error 2
make[3]: **\* [deb] Error 2
make[2]: **\* [deb] Error 2
make[2]: Leaving directory `/home/ahmed/ONL/components/amd64/initrd-amd64'
Traceback (most recent call last):
  File "/home/ahmed/ONL/tools/onlpkg.py", line 289, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/ahmed/ONL/tools/onlpkg.py", line 159, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/ahmed/ONL/components/amd64/initrd-amd64', 'deb')' returned non-zero exit status 2
make[1]: *** [component-deps] Error 1
make[1]: Leaving directory`/home/ahmed/ONL/builds/components'
make: **\* [all-components] Error 2

**Comment by capveg** [comment] 2015-07-22 13:29
I believe this is related to the fact that sourceforge.com is down (read:
at least this one may not be our fault :-).  Jeff and I are working on a
fix in the backend, so please hold tight.

- Rob
.

**Comment by ahmedcs** [comment] 2015-07-22 14:26
Thanks Rob, 

I tried to figure what was causing the problem but had no idea of how the build process is working.
Appreciate your help. I am actually trying to build the binary for two reasons 

First as it would solve my issue #120 , which i am bashing my head with now. I even tried to install older versions of ONL installer but with no luck (same problem routes are in the chip as the output from killall -USR1 orc confirms) but packets are captured by tcpdump (which suggests software switching is happening).

Second is later i will be doing research using ONL, so i would be happy to work on the build process

Cheers

**Comment by ahmedcs** [comment] 2015-07-23 06:29
Hello Rob,

I am trying the build now but i am getting different compilation error

export ONL=`pwd` && make -C $ONL/builds/components
make[1]: Entering directory `/home/ahmed/ONL/builds/components'
WARNING:onlpkg:no matching packages for indigo-ofdpa-ofagent (powerpc)
INFO:onlpkg:can be built locally at /home/ahmed/ONL/components/powerpc/indigo-ofdpa-ofagent
make[2]: Entering directory `/home/ahmed/ONL/components/powerpc/indigo-ofdpa-ofagent'
rm -rf /home/ahmed/ONL/components/any/indigo-ofdpa-ofagent/deb/debuild-powerpc
cp -R /home/ahmed/ONL/components/any/indigo-ofdpa-ofagent/deb/debuild /home/ahmed/ONL/components/any/indigo-ofdpa-ofagent/deb/debuild-powerpc
make -C /home/ahmed/ONL/components/any/indigo-ofdpa-ofagent deb DEBUILD_DIR=debuild-powerpc
make[3]: Entering directory `/home/ahmed/ONL/components/any/indigo-ofdpa-ofagent'
WARNING:onlpkg:no matching packages for ofdpa-2.0-closed (powerpc)
INFO:onlpkg:can be built locally at /home/ahmed/ONL/components/powerpc/ofdpa-2.0-closed
make[4]: Entering directory `/home/ahmed/ONL/components/powerpc/ofdpa-2.0-closed'
rm -rf /home/ahmed/ONL/components/any/ofdpa-2.0-closed/deb/debuild-powerpc
cp -R /home/ahmed/ONL/components/any/ofdpa-2.0-closed/deb/debuild /home/ahmed/ONL/components/any/ofdpa-2.0-closed/deb/debuild-powerpc
make -C /home/ahmed/ONL/components/any/ofdpa-2.0-closed deb DEBUILD_DIR=debuild-powerpc
make[5]: Entering directory `/home/ahmed/ONL/components/any/ofdpa-2.0-closed'
WARNING:onlpkg:no matching packages for kernel-85xx-headers (powerpc)
INFO:onlpkg:found at /home/ahmed/ONL/components/powerpc/linux/kernel-85xx/deb/debuild/debian
INFO:onlpkg:can be built locally at /home/ahmed/ONL/components/powerpc/linux/kernel-85xx
make[6]: Entering directory `/home/ahmed/ONL/components/powerpc/linux/kernel-85xx'
make -C deb
make[10]: Nothing to be done for `all'.
cd debuild-powerpc; debuild --prepend-path=/usr/lib/ccache -eONL -eBUILD_DIR_BASE  -apowerpc -b -us -uc
/bin/bash: line 0: cd: debuild-powerpc: No such file or directory
debuild: fatal error at line 629:
cannot find readable debian/changelog anywhere!
Are you in the source code tree?
make[8]: *** [deb] Error 255
make[7]: *** [deb] Error 2
make[6]: *** [deb] Error 2
make[6]: Leaving directory `/home/ahmed/ONL/components/powerpc/linux/kernel-85xx'
Traceback (most recent call last):
  File "/home/ahmed/ONL/tools/onlpkg.py", line 291, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/ahmed/ONL/tools/onlpkg.py", line 161, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/ahmed/ONL/components/powerpc/linux/kernel-85xx', 'deb')' returned non-zero exit status 2
make[5]: *** [component-deps] Error 1
make[5]: Leaving directory `/home/ahmed/ONL/components/any/ofdpa-2.0-closed'
make[4]: *** [deb] Error 2
make[4]: Leaving directory `/home/ahmed/ONL/components/powerpc/ofdpa-2.0-closed'
Traceback (most recent call last):
  File "/home/ahmed/ONL/tools/onlpkg.py", line 291, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/ahmed/ONL/tools/onlpkg.py", line 161, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/ahmed/ONL/components/powerpc/ofdpa-2.0-closed', 'deb')' returned non-zero exit status 2
make[3]: *** [component-deps] Error 1
make[3]: Leaving directory `/home/ahmed/ONL/components/any/indigo-ofdpa-ofagent'
make[2]: *** [deb] Error 2
make[2]: Leaving directory `/home/ahmed/ONL/components/powerpc/indigo-ofdpa-ofagent'
Traceback (most recent call last):
  File "/home/ahmed/ONL/tools/onlpkg.py", line 291, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/ahmed/ONL/tools/onlpkg.py", line 161, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/ahmed/ONL/components/powerpc/indigo-ofdpa-ofagent', 'deb')' returned non-zero exit status 2
make[1]: *** [component-deps] Error 1
make[1]: Leaving directory `/home/ahmed/ONL/builds/components'
make: *** [all-components] Error 2

Is it due to same error above?!

Thanks

**Comment by capveg** [comment] 2015-07-27 03:22
Can you re-try this?  I believe the problem is fixed now.

**Comment by ahmedcs** [comment] 2015-07-27 04:41
The problem is fixed Rob, Thanks

But what about the other issues, #126 and #120 

I would appreciate any help regarding it as my research is stuck at this point

Thanks

**Comment by GrantMackey-WDC** [comment] 2016-02-03 21:58
I'd like to follow up on Ahmedcs with his build issue. 

Here is my build fail (for x86 and powerpc)

dpkg-deb: building package `platform-config-x86-64-wnc-sst1-n1-r0' in `../platform-config-x86-64-wnc-sst1-n1-r0_0.1.0bsn1~ubuntu1_all.deb'.
 dpkg-genchanges -b >../platform-config-x86-64-wnc-sst1-n1-r0_0.1.0bsn1~ubuntu1_amd64.changes
dpkg-genchanges: binary-only upload - not including any source code
 dpkg-source --after-build debuild
dpkg-buildpackage: binary only upload (no source included)
Now running lintian...
E: platform-config-x86-64-wnc-sst1-n1-r0: description-synopsis-is-duplicated
W: platform-config-x86-64-wnc-sst1-n1-r0: script-not-executable lib/platform-config/x86-64-wnc-sst1-n1-r0/python/onlpc.py
W: platform-config-x86-64-wnc-sst1-n1-r0: executable-not-elf-or-script lib/platform-config/x86-64-wnc-sst1-n1-r0/boot/x86-64-wnc-sst1-n1-r0-devices.sh
Finished running lintian.
GNUPGHOME=/home/gmackey/ONL/make/default_sign/gnupg dpkg-sig --sign builder *all*.deb  \
	&& echo Packages Signed # sign packages
Processing platform-config-x86-64-wnc-sst1-n1-r0_0.1.0bsn1~ubuntu1_all.deb...
gpg: WARNING: unsafe permissions on homedir `/home/gmackey/ONL/make/default_sign/gnupg'
Signed deb platform-config-x86-64-wnc-sst1-n1-r0_0.1.0bsn1~ubuntu1_all.deb
Packages Signed
/home/gmackey/ONL/tools/onlpkg.py --add-pkg *all*.deb
INFO:onlpkg:adding new package platform-config-x86-64-wnc-sst1-n1-r0_0.1.0bsn1~ubuntu1_all.deb...
INFO:onlpkg:removed previous install directory /home/gmackey/ONL/debian/installs/all/platform-config-x86-64-wnc-sst1-n1-r0...
rm *all*.deb
rm -rf debuild/debian/tmp debuild/debian/platform-config-x86-64-wnc-sst1-n1-r0/ debuild/debian/platform-config-x86-64-wnc-sst1-n1-r0-dbg || echo rm failed
cp patches/busybox-001-init-quiet-restart.patch patches/busybox-002-checkpass-command.patch buildroot/package/busybox/
cp: target `buildroot/package/busybox/' is not a directory
make[7]: *** [setup] Error 1
make[6]: *** [/home/gmackey/ONL/submodules/loader/.setup.done] Error 2
make[5]: *** [component] Error 2
make[4]: *** [deb] Error 2
make[3]: *** [deb] Error 2
make[2]: *** [deb] Error 2
make[2]: Leaving directory `/home/gmackey/ONL/components/amd64/initrd-amd64'
Traceback (most recent call last):
  File "/home/gmackey/ONL/tools/onlpkg.py", line 301, in <module>
    check_call(('make', '-C', buildpath, 'deb',))
  File "/home/gmackey/ONL/tools/onlpkg.py", line 167, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-C', '/home/gmackey/ONL/components/amd64/initrd-amd64', 'deb')' returned non-zero exit status 2
make[1]: *** [component-deps] Error 1
make[1]: Leaving directory `/home/gmackey/ONL/builds/components'
make: *** [all-components] Error 2

My error pops up from line 69 of the $ONL/submodules/loader/Makefile 
setup: platform-configs
	cp $(wildcard patches/busybox*.patch) buildroot/package/busybox/  --> this fails
	cp $(wildcard patches/kexec*.patch) buildroot/package/kexec/
	sed -i 's%^DOSFSTOOLS_SITE =.*%DOSFSTOOLS_SITE = http://downloads.openwrt.org/sources%' buildroot/package/dosfstools/dosfstools.mk
	sed -i 's%^UEMACS_SITE =.*%UEMACS_SITE = http://www.kernel.org/pub/linux/kernel/uemacs%;s%^UEMACS_SOURCE =.*%UEMACS_SOURCE = em-$$(UEMACS_VERSION).tar.gz%' buildroot/package/uemacs/uemacs.mk
	mkdir -p buildroot/package/jq
	cp patches/jq.mk buildroot/package/jq/jq.mk
	cp patches/jq.Config.in buildroot/package/jq/Config.in
	sed -i '/[/]jq[/]/d' buildroot/package/Config.in
	sed -i '/[/]yajl[/]/a\source "package/jq/Config.in"' buildroot/package/Config.in
	mkdir -p $(BUILDROOT_ARCHDIRS)
	$(foreach a,$(ARCHS),cp buildroot.config-$(a) buildroot-$(a)/.config ;)

I had to make a modifications to the .gitmodules files because they defaulted to git:// (rather than https://) for the clone operations and this was hanging. I guess that when I went to clone the submodules repos not everything was getting pulled, which is why these directories don't exist?

 - Grant

**Closed** 2018-05-02 16:42 UTC
